### ISSUE TITLE
OT.$.browser is not a function

### ISSUE THREAD

**Issue by Jagdeep-Sing** [opentok/accelerator-sample-apps-js#18] opened 2018-01-19 07:42 UTC
Previously the app was working fine but from today morning, it always show this error message in browser.i also try to build new app by downloading from here but it also show same error.
can anyone please help?
the error is coming from opentok-screensharing.js file
I'm using: vanilla-js-sample-app
I also try to download opentok.min.js file and include it from local but same error
@maikthomas or any other dev reading this please help

Error is :
> Uncaught TypeError: OT.$.browser is not a function &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;opentok-screen-sharing.js:395 
    at _validateExtension (opentok-screen-sharing.js:395)
    at _validateOptions (opentok-screen-sharing.js:422)
    at new ScreenSharingAccPack (opentok-screen-sharing.js:442)
    at initPackages (opentok-acc-core.js:8986)
    at opentok-acc-core.js:9018
    at i (eventing.js:258)
    at innerEventingMixin.js:59

and the line from where error is coming, is : 
`if (OT.$.browser() === 'Chrome') {some code here}`

**Comment by maikthomas** [comment] 2018-01-19 11:24
@Jagdeep-Sing yes it looks like this has been caused by the 2.13 release of the opentok.js client.
To fix for now I would suggest specifying the version at 2.12.
If you are following the vanilla-js example this will be in the index.html here https://github.com/opentok/accelerator-sample-apps-js/blob/master/vanilla-js-sample-app/public/index.html#L10
swap 
  `<script src="https://static.opentok.com/v2/js/opentok.min.js"></script>`
for
    `<script src="https://static.opentok.com/v2.12/js/opentok.min.js"></script>`

**Comment by Jagdeep-Sing** [comment] 2018-01-19 11:28
Yes, I changed and its working. thanks @maikthomas for your kind support :+1:

**Comment by maikthomas** [comment] 2018-01-19 11:32
Great! Thanks for alerting us to this issue. I'll keep the issue open until we've got a general fix up.

**Comment by maikthomas** [comment] 2018-01-24 15:38
This issue has been fixed in https://github.com/opentok/accelerator-screen-sharing-js.
You can now use the version 2.13 of opentok.js if you upgrade [opentok-screen-sharing](https://www.npmjs.com/package/opentok-screen-sharing) to version 1.0.28.

I'll change the package.json files for the sample apps to specify that version or higher before I consider this issue closed.

**Comment by maikthomas** [comment] 2018-01-25 09:13
Version requirements updating in package.json files. Closing issue.

**Closed by maikthomas** 2018-01-25 09:13 UTC

**Comment by Jagdeep-Sing** [comment] 2018-01-27 08:52
How do I update to latest version of screen sharing?

**Comment by maikthomas** [comment] 2018-01-29 10:08
You can do 
`npm install --save opentok-screen-sharing@^1.0.28`
which will update and save the version requirement in your package.json.
If you are running the vanilla sample app then you will also need to run
`npm run build`
to copy those files over to the components folder.

**Comment by Jagdeep-Sing** [comment] 2018-01-29 13:31
on running this : 
` npm install --save opentok-screen-sharing@^1.0.28`
I got : 

> npm WARN vanilla-js-sample-app@1.0.0 No repository field.`
This we can ignore i think.

But, on running this : 
` npm run build`

I got : 

    module.js:471
    throw err;
    ^

    Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/myAppPath/vanilla-js-sample-app/node_modules/.bin/mkdirp:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

    npm ERR! Linux 4.14.12-xxxx-std-ipv6-64
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    npm ERR! node v6.12.3
    npm ERR! npm  v3.10.10
    npm ERR! code ELIFECYCLE
    npm ERR! vanilla-js-sample-app@1.0.0 build: `mkdirp public/js/components && npm run cp-annotation && npm run cp-archiving && npm run cp-screen-sharing && npm run cp-text-chat && npm run cp-logging && npm run cp-core`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the vanilla-js-sample-app@1.0.0 build script 'mkdirp public/js/components &&           npm run cp-annotation && npm run cp-archiving && npm run cp-screen-sharing && npm run cp-text-chat && npm run cp-logging && npm run cp-core'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the vanilla-js-sample-app package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     mkdirp public/js/components && npm run cp-annotation && npm run cp-archiving &&         npm run cp-screen-sharing && npm run cp-text-chat && npm run cp-logging && npm run cp-core
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs vanilla-js-sample-app
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls vanilla-js-sample-app
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /var/www/html/myAppPath/vanilla-js-sample-app/npm-debug.log

**Comment by maikthomas** [comment] 2018-01-29 14:21
@Jagdeep-Sing I am not able to reproduce this error.
Have you modified the build commands in package.json in any way?

**Comment by Jagdeep-Sing** [comment] 2018-01-31 09:41
@maikthomas I moved the app.js file to some other location. this is the reason?

**Comment by maikthomas** [comment] 2018-01-31 09:54
I don't think so, but this isn't reproducible on my end.
If you want to debug this I would say first, do `npm install` again to make sure you have the dependencies.
Then break the failing script, 'build' into smaller pieces to test. The script is:
   ` "build": "mkdirp public/js/components && npm run cp-annotation && npm run cp-archiving && npm run cp-screen-sharing && npm run cp-text-chat && npm run cp-logging && npm run cp-core"`

To debug it, run each command separately.
1) The `mkdirp` command won't work outside of the script unless you have `mkdirp` globally installed, so just check if that folder (public/js/components) exists, if not then create it.
2) Then other parts individually to see where it fails i.e.:
`npm run cp-annotation`
`npm run cp-archiving`
`npm run cp-screen-sharing`
`npm run cp-text-chat`
`npm run cp-logging`
`npm run cp-core`
